name: Ubuntu

on: [push, pull_request]

jobs:
  build-test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]

    steps:
    - uses: actions/checkout@v1
    - name: install-build-dependencies
      run: sudo apt-get install libeigen3-dev
    - name: submodule
      run: git submodule update --init --recursive
    - name: cmake
      run: cmake . -DCOLORUTIL_BUILD_TESTS=ON
    - name: make
      run: make
    - name: ctest
      run: ctest --output-on-failure
